### PR TITLE
update dependencies to reveal.js 3.2.0 and highlightjs 9.0.0

### PR DESCRIPTION
**Pull request by riezebosch**

### CODE REVIEW

**Comment by janraasch** [comment]
Hi @riezebosch, 

thank you for the pr. Just a few questions.

1. Have you tested this locally? 
2. Are there any important (e.g. *breaking*) changes (for example in the v9 *major* release of `highlightjs`) we should be aware of?

**Comment by riezebosch** [comment]
1. I've tried it locally with some C# and some XML samples using the VS.css stylesheet and it looked good to me.
1. I don't know of any breaking changes. There are still some issues open but it doesn't seem to me about regression or breaking backwards compatibility.

Another thing, I just found out there is also a 9.1.0 release available which was published only 6 days ago.

**Comment by janraasch** [comment]
Very well. Feel free to update the `highlightjs` version to `v9.1.0` then.

**Comment by riezebosch** [comment]
Was looking at the wrong repository. Bower uses a shim repository that is still at 9.0.0 so current PR is pointing to the latest release.

**Pull request merged**
